typography_spectrum: 0.5245470087975264
color:
  brandColors:
    - '#070707'
    - '#fefefd'
    - '#d5331b'
    - '#e59b15'
    - '#feda1c'
  brandStrength: 0.5
  lightness: 0.16221422632224858
  saturation: 0.1875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.59442
analytics:
  google: null
  facebook: null
  twitter: null
name: DayGlo Digital Art
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Welcome
description: Where art and light become one.
purpose: []
