name: DayGlo Digital Art
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5245470087975264
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#fefefd'
    - '#d5331b'
    - '#e59b15'
    - '#feda1c'
  brandStrength: 0.9759321713354439
  lightness: 0.16221422632224858
  saturation: 0.16966573288664222
  rhythmicContrast: 0.2876477208919823
purpose: []
